###################################
### GENERAL, HEADER & META TAGS ###
###################################

# Logo for your blog
logo: "/assets/logo.png"

# Give your blog a meaningful title. This is used for the HTML title attribute
title: "Lines Blog - A Blog about Ruby on Rails"

# Place the name of your blog or a short title here
title_short: "Lines Blog"

# Short description for your blog
short_description: "A Ruby on Rails Developer's Blog"

# meta description tag
meta_description: "A Ruby on Rails Developer's Blog"

# meta tag for author
meta_author: "John Doe"

# your keywords
keywords: "Lines, Blog, Ruby on Rails"

# OpenGraph logo
og_logo: "http://www.opoloo.de/assets/opoloogo.png"

# Geo tags for position and address
geo_position: "50.00; 8.27"
geo_address: "Opoloo, Emmerich-Josef-Str. 1A, 55116 Mainz"


#################
### ATOM FEED ###
#################

# give your feed a title
feed_title: "Lines Blog - A Blog about Ruby on Rails"

# full URL to the feed logo
feed_logo: "http://blog.opoloo.com/assets/opoloo_feed.png" # aspect ratio should be 2:1

#full URL to the favicon
feed_favicon: "http://blog.opoloo.com/favivon.ico" # aspect ratio should be 1:1

#####################
### APP SPECIFICS ###
#####################

# Your apps secret token. Generate a new one with 'rake secret'
secret_token: "afa4a436180a2febe9b814c6a57b6f3ad298aa82ce0ab4c9e8238713764b665e978f9fad8146587b6cf4a518de4a8f0eac1156cf43a778548e0082629d099fef"

# Environment dependent configuration. Place your URLs here
development:
  host: "localhost:3000"
test:
  host: "test.local"
production:
  host: "blog.opoloo.com"